const List<Map> data = [
  {"key": "Nikola Tesla", "use": "I don't care they stole my idea, I care they don't have any of their own."},
  {"key": "Albert Einstein", "use": "Time is relative."},
  {"key": "Elon Musk", "use": "I've actually not read any books on time management."},
  {"key": "Steve Jobs", "use": "We're just enthusiastic about what we do."},
  {"key": "Alan Turing", "use": "Science is a different equation, Religion is a boundary condition."},
  {"key": "Nikola Tesla", "use": "Of all things, I like books best."},
  {"key": "Albert Einstein", "use": "All religions, arts and science are branches of same tree."},
  {"key": "Elon Musk", "use": "Jeff who...?"},
  {"key": "Steve Jobs", "use": "Things don't have to change the world to be important."},
  {"key": "Alan Turing", "use": "Codes are puzzle. A game, just like any other game."},
  {"key": "Nikola Tesla", "use": "It's not love you make. It's the love you give."},
  {"key": "Albert Einstein", "use": "A man should look for what is, and not for what he thinks should be."},
  {"key": "Elon Musk", "use": "Human should be multi-planet species."},
  {"key": "Steve Jobs", "use": "Your time is limited, so don't waste it living someone else's life."},
  {"key": "Alan Turing", "use": "Mathematical reasoning may be regarded."},
  {"key": "Nikola Tesla", "use": "The present is theirs, the future, for which I really worked, is mine."},
  {"key": "Albert Einstein", "use": "The most beautiful experience we can have is the mysterious."},
  {"key": "Elon Musk", "use": "We have a strict  'no as* holes policy' at SpaceX ."},
  {"key": "Steve Jobs", "use": "Stay hungry. Stay foolish."},
  {"key": "Alan Turing", "use": "No, I am not interested in developing a powerful brain."},
  {"key": "Nikola Tesla", "use": "What one man calls god, another calls the law of Physics."},
  {"key": "Albert Einstein", "use": "A human is part of a whole called by us 'Universe'."},
  {"key": "Elon Musk", "use": "Don't be afraid of new arenas."},
  {"key": "Steve Jobs", "use": "Innovation distinguishes between a leader and a follower."},
  {"key": "Alan Turing", "use": "If a machine is expected to be infallible, it cannot also be intelligent."},
  {"key": "Nikola Tesla", "use": "Great movements are born great oppurtunity."},
  {"key": "Albert Einstein", "use": "Life is like riding a bicycle."},
  {"key": "Elon Musk", "use": "I think it is possible for ordinary people to choose to be extraordinary."},
  {"key": "Steve Jobs", "use": "Creativity is just connecting things."},
  {"key": "Alan Turing", "use": "Those who can imagine anything, can create the impossible."},
  {"key": "Nikola Tesla", "use": "Inventors don't have time for married life."},
  {"key": "Albert Einstein", "use": "I love to travel, but I hate to arrive."},
  {"key": "Elon Musk", "use": "I could either watch it happen or be a part of it."},
  {"key": "Yama Buddha", "use": "If god really exists then he must be sleeping."},
  {"key": "Alan Turing", "use": "My little computer said such a funny thing this morning."},
  {"key": "Nikola Tesla", "use": "The progressive development of a man is vitally dependent on invension."},
  {"key": "Albert Einstein", "use": "I have no special talent. I am only passionately curious."},
  {"key": "Elon Musk", "use": "I woukd like to die on mars. Just not on impact."},
  {"key": "Bijay Chor ", "use": "Kaali mata , divine pover."},
  {"key": "Mark Zuckerberg", "use": "The biggest risk is not taking any risk."},
  {"key": "Aayush Dhakal", "use": "Nam nai kafii xa."},
  {"key": "Albert Einstein", "use": "Science can flourish only in an atmosphere of free speech."},
  {"key": "Elon Musk", "use": "I judge book by it's cover."},
  {"key": "Steve Jobs", "use": "Everyone should learn programming language."},
  {"key": "Mark Zuckerberg", "use": "Find that thing you are super passionate about."},
  {"key": "Nikola Tesla", "use": "Two paradoxes are better than one they may even suggest a solution."},
  {"key": "Aayush Dhakal", "use": "Jaile hatar ma."},
  {"key": "Elon Musk", "use": "You shouldn't give up unless you are forced to give up."},
  {"key": "Steve Jobs", "use": "My job is not to be easy on people. My job is to make them better."},
  {"key": "Aayush Dhakal", "use": "Future is devil and past is evil."},
  {"key": "Nikola Tesla", "use": "If I have seen further it is by my standing on the soulders of Giants."},
  {"key": "Albert Einstein", "use": "Unthinking respect for authority is greatest enemy of truth."},
  {"key": "Elon Musk", "use": "Baby Doge,doo,doo,doo,doo,doo."},
  {"key": "Eminem", "use": "Fu*k Donald Trump."},
  {"key": "Edward Snowden", "use": "What is right is not always the same as what is legal."}
];
